<?php

namespace voidworks\ppitems\items\etc;

use pocketmine\entity\Ageable;
use pocketmine\entity\effect\EffectInstance;
use pocketmine\entity\effect\VanillaEffects;
use pocketmine\entity\EntityDataHelper;
use pocketmine\entity\EntityFactory;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Living;
use pocketmine\entity\Location;
use pocketmine\entity\NeverSavedWithChunkEntity;
use pocketmine\event\entity\EntityDamageByEntityEvent;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\inventory\ArmorInventory;
use pocketmine\item\VanillaItems;
use pocketmine\math\Vector3;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;
use pocketmine\network\mcpe\protocol\types\entity\EntityMetadataCollection;
use pocketmine\network\mcpe\protocol\types\entity\EntityMetadataFlags;
use pocketmine\player\Player;
use pocketmine\utils\TextFormat;
use pocketmine\world\World;
use voidworks\ppitems\Loader;
use voidworks\ppitems\utils\ClosureCancellableTask;

final class MinionEntity extends Living implements Ageable, NeverSavedWithChunkEntity {

    public const TAG_BABY = "IsBaby";

    static public function register(): void {
        EntityFactory::getInstance()->register(self::class, function(World $world, CompoundTag $nbt) : MinionEntity {
            return new MinionEntity(EntityDataHelper::parseLocation($nbt, $world), $nbt);
        }, ["ppitems:minion_entity"]);
    }

    public function __construct(Location $location, ?CompoundTag $nbt = null, protected ?Player $owner = null){
        parent::__construct($location, $nbt);
    }

    protected int $waitToAttackTime = 0;

    protected Vector3 $nextMovementTo;

    protected function initEntity(CompoundTag $nbt) : void{
        parent::initEntity($nbt); // TODO: Change the autogenerated stub

        if($this->owner === null && !$this->isClosed()){
            $this->flagForDespawn();
            return;
        }
        $this->nextMovementTo = $this->getPosition();
        $this->getEffects()->add(new EffectInstance(VanillaEffects::RESISTANCE(), infinite: true));
        $this->setMaxHealth(20);
        $this->setHealth(20);
        $this->setNameTag(TextFormat::colorize("&r&e{$this->owner->getName()}'s Minion"));
        $this->setNameTagVisible();
        $this->setNameTagAlwaysVisible();
        $this->getArmorInventory()->setContents([
            ArmorInventory::SLOT_HEAD => VanillaItems::DIAMOND_HELMET(),
            ArmorInventory::SLOT_CHEST => VanillaItems::DIAMOND_CHESTPLATE(),
            ArmorInventory::SLOT_LEGS => VanillaItems::DIAMOND_LEGGINGS(),
            ArmorInventory::SLOT_FEET => VanillaItems::DIAMOND_BOOTS()
        ]);

        $this->setScale(0.6);
    }

    public function getName() : string{
        return "Minion";
    }

    public function onUpdate(int $currentTick) : bool{
        if($currentTick % 10 === 0){
            $this->searchTarget();
        }
        return parent::onUpdate($currentTick) || $this->hasMovementUpdate();
    }

    protected function getInitialSizeInfo() : EntitySizeInfo{
        return new EntitySizeInfo(0.975, 0.3);
    }

    public static function getNetworkTypeId() : string{
        return EntityIds::ZOMBIE;
    }

    protected function syncNetworkData(EntityMetadataCollection $properties) : void{
        parent::syncNetworkData($properties);
        $properties->setGenericFlag(EntityMetadataFlags::BABY, $this->isBaby());
    }

    public function saveNBT() : CompoundTag{
        $nbt = parent::saveNBT();
        $nbt->setByte(self::TAG_BABY, $this->isBaby() ? 1 : 0);
        return $nbt;
    }

    /*
     * @return void
     */
    public function onCollideWithPlayer(Player $player) : void{
        if($this->owner === null && !$this->isClosed()){
            $this->flagForDespawn();
            return;
        }

        if($player === $this->owner){
            return;
        }

        if(++$this->waitToAttackTime % 20 === 0){
            $ev = new EntityDamageByEntityEvent($this, $player, EntityDamageEvent::CAUSE_ENTITY_ATTACK, 4);
            $player->attack($ev);
        }
    }

    public function startTicking(): void {
        Loader::getInstance()->getScheduler()->scheduleRepeatingTask(new ClosureCancellableTask(
            $this->moveToNextPosition(...),
            fn() => !$this->isAlive() || $this->isClosed() || $this->isFlaggedForDespawn()
        ), 20);
    }

    /**
     * @return void
     */
    protected function moveToNextPosition() : void{
        $target = $this->nextMovementTo;
        $pos = $this->getPosition();

        $dx = $target->x - $pos->x;
        $dz = $target->z - $pos->z;

        $distance = sqrt($dx * $dx + $dz * $dz);
        if($distance < 0.0025){
            $this->motion->x = 0;
            $this->motion->z = 0;
            return;
        }

        $dx /= $distance;
        $dz /= $distance;

        $speed = mt_rand(15, 22) / 100;

        $this->motion->x = $dx * $speed;
        $this->motion->z = $dz * $speed;

        $this->lookAt($target);
        $front = $pos->add($dx, 0, $dz);
        $block = $this->getWorld()->getBlock($front);

        if($block->isSolid() && $this->onGround){
            $this->jump();
        }
    }

    public function getJumpVelocity() : float{
        return 0.57;
    }

    /**
     * @return void
     */
    protected function searchTarget(): void {
        if($this->owner === null){
            if(!$this->isClosed()){
                $this->flagForDespawn();
            }
            return;
        }

        foreach($this->getWorld()->getNearbyEntities($this->boundingBox->expandedCopy(20, 20, 20), $this) as $entity){
            if(!$entity instanceof Player){
                continue;
            }

            if($entity === $this->owner){
                continue;
            }

            $this->nextMovementTo = $entity->getLocation();
            break;
        }
    }

    public function isBaby() : bool{
        return true;
    }
}