<?php

namespace voidworks\ppitems\command\parent;

use abstractplugin\command\Argument;
use pocketmine\command\CommandSender;
use pocketmine\permission\DefaultPermissions;
use pocketmine\Server;
use pocketmine\utils\TextFormat;
use voidworks\ppitems\Loader;

final class GiveArgument extends Argument {

    public function __construct() {
        parent::__construct('give', DefaultPermissions::ROOT_OPERATOR);
    }

    public function onConsoleExecute(CommandSender $sender, string $commandLabel, array $args): void {
        if (count($args) < 2) {
            $sender->sendMessage(TextFormat::RED . 'Usage: /' . $commandLabel . ' <player> <partnerItem>');

            return;
        }

        $player = Server::getInstance()->getPlayerExact($args[0]);
        $partnerItem = Loader::getInstance()->getPartnerItemsHandler()->getPartnerItemByIdentifier($args[1]);

        if ($player === null) {
            $sender->sendMessage(TextFormat::RED . 'You must enter a valid player name.');

            return;
        }

        if ($partnerItem === null) {
            $sender->sendMessage(TextFormat::RED . 'You must enter a valid partner item.');

            return;
        }

        if ($player->getInventory()->canAddItem($partnerItem->getItem())) {
            $player->getInventory()->addItem($partnerItem->getItem());

            $player->sendMessage(TextFormat::GREEN . 'You have received a partner item: ' . $partnerItem->getDisplayName() . TextFormat::GREEN . '.');
            $sender->sendMessage(TextFormat::GREEN . 'You have successfully given ' . $partnerItem->getDisplayName() . TextFormat::GREEN . ' to ' . TextFormat::AQUA . $player->getName() . TextFormat::GREEN . '.');
        } else {
            $sender->sendMessage(TextFormat::RED . 'You cannot add items to this player. He has full inventory.');
        }
    }

    public function getPermission(): ?string {
        return parent::getPermission(); // TODO: Change the autogenerated stub
    }
}